name: Run tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
    - name: Chekout
      uses: actions/checkout@v1
    - name: instalar as deps do server
      uses: bahmutov/npm-install@v1
      with:
        working-directory: server
    - name: instalar as deps do web
      uses: bahmutov/npm-install@v1
      with:
        working-directory: web
    - name: Components & API & UI Tests
      uses: cypress-io/github-action/@v2
      with:
        working-directory: web
        install: false
        start: npm run start:ci
        wait-on: "http://localhost:3000"
    - name: Upload Screenshots
      uses: actions/upload-artifact@v2.2.0
      if: failure()
      with:
        name: screenshots
        path: web/cypress/screenshots
    - name: Upload Videos
      uses: actions/upload-artifact@v2.2.0
      if: always()
      with:
        name: videos
        path: web/cypress/videos
